# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{youthtree-js}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Darcy Laycock"]
  s.date = %q{2010-08-16}
  s.description = %q{Shared Javascript tools across YouthTree apps.}
  s.email = %q{sutto@sutto.net}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "coffeescripts/youth_tree.coffee",
     "coffeescripts/youth_tree/flickr_gallery.coffee",
     "coffeescripts/youth_tree/gallery.coffee",
     "javascripts/plugins/jquery/cycle.js",
     "javascripts/youth_tree.js",
     "javascripts/youth_tree/flickr_gallery.js",
     "javascripts/youth_tree/gallery.js",
     "lib/youthtree-js.rb",
     "youthtree-js.gemspec"
  ]
  s.homepage = %q{http://github.com/YouthTree/youthtree-js}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Shared Javascript tools across YouthTree apps.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

