# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{youthtree-js}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Darcy Laycock"]
  s.date = %q{2010-12-02}
  s.description = %q{Shared Javascript tools across YouthTree apps.}
  s.email = %q{sutto@sutto.net}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "coffeescripts/youth_tree.coffee",
    "coffeescripts/youth_tree/disqus.coffee",
    "coffeescripts/youth_tree/flickr.coffee",
    "coffeescripts/youth_tree/flickr/gallery.coffee",
    "coffeescripts/youth_tree/forms/ck_editor.coffee",
    "coffeescripts/youth_tree/forms/convertable_editor.coffee",
    "coffeescripts/youth_tree/forms/date_picker.coffee",
    "coffeescripts/youth_tree/forms/value_cloner.coffee",
    "coffeescripts/youth_tree/gallery.coffee",
    "coffeescripts/youth_tree/util.coffee",
    "javascripts/youth_tree.js",
    "javascripts/youth_tree/ck_editor.js",
    "javascripts/youth_tree/convertable_editor.js",
    "javascripts/youth_tree/disqus.js",
    "javascripts/youth_tree/flickr.js",
    "javascripts/youth_tree/flickr/gallery.js",
    "javascripts/youth_tree/forms/ck_editor.js",
    "javascripts/youth_tree/forms/convertable_editor.js",
    "javascripts/youth_tree/forms/date_picker.js",
    "javascripts/youth_tree/forms/value_cloner.js",
    "javascripts/youth_tree/gallery.js",
    "javascripts/youth_tree/util.js",
    "lib/youthtree-js.rb",
    "youthtree-js.gemspec"
  ]
  s.homepage = %q{http://github.com/YouthTree/youthtree-js}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Shared Javascript tools across YouthTree apps.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

